version: '3.8'


services:
  postgres-demo:
    image: postgres:15.2
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: security_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: