spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/spring_security
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/changelog.xml

application:
  security:
    jwt:
      secret-key: my-32-character-ultra-secure-and-ultra-long-secret
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days


